[package]
name = "data-streaming-service"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
repository = "https://github.com/diem/diem"
description = "The data streaming service that sends data notifications to clients"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
async-trait = "0.1.42"
enum_dispatch = "0.3.5"
futures = "0.3.12"
itertools = "0.10.0"
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"
tokio = { version = "1.8.1", features = ["full"] }
tokio-stream = "0.1.4"

channel = { path = "../../../common/channel" }
diem-config = { path = "../../../config" }
diem-crypto = { path = "../../../crypto/crypto" }
diem-data-client = { path = "../../diem-data-client" }
diem-id-generator = { path = "../../../common/id-generator" }
diem-infallible = { path = "../../../common/infallible" }
diem-logger = { path = "../../../common/logger" }
diem-types = { path = "../../../types" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }

[dev-dependencies]
claim = "0.5.0"
rand = "0.8.3"
tokio = { version = "1.8.1", features = ["full"] }

diem-types = { path = "../../../types" }
storage-service-types = { path = "../../storage-service/types" }
